# Site settings
title: FMI Weather data downloader
email: 
description: > # this means to ignore newlines until "baseurl:"
  A simple GUI for downloading weather observation data from FMI's dataservice to Excel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tumetsu.github.io/Ilmatieteenlaitoksen-saadata-lataaja" # the base hostname & protocol for your site
twitter_username: tumetsu
github_username:  tumetsu

# Build settings
markdown: kramdown
